name: Publish NuGet package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Smetik.ArrayTools.sln

      - name: Build
        run: dotnet build Smetik.ArrayTools.sln --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack Smetik.ArrayTools/Smetik.ArrayTools.csproj --configuration Release --no-build -o ./nupkg

      - name: Add GitHub Packages source
        run: dotnet nuget add source --username Smetik --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Smetik/index.json"

      - name: Publish package
        run: dotnet nuget push ./nupkg/*.nupkg --source github --skip-duplicate